package Airline.Model;

//24 European airports
public enum Airport {
    DUBLIN, SARAJEVO, HOMS, TALLINN, MOSCOW, EDINBURGH, ANKARA,
    PRAGUE, PRISTINA, ZAGREB, PODGORICA, WARSAW, VILNIUS, TIRANA,
    TBILISI, KIEV, SKOPJE, SOFIA, GIBRALTAR, LJUBLJANA, MINSK,
    NICOSIA, BACU, BELFAST, BERN, BRATISLAVA, BUCHAREST, CADIFF,
    BUDAPEST, CHISINAU, NUUK
}
